### ISSUE TITLE
add liveness/readyness enpoints

### ISSUE THREAD

**Issue by benedikt-bartscher** [nroi/flexo#100]
Adding a liveness/readyness endpoint would be great for deployment with Kubernetes. I could publish my helm chart if someone is interested.

**Comment by nroi** [comment]
There's the `/status` endpoint already available, does that work for you? It just returns `200 OK`.

If not, please share a few more details about what you expect from this endpoint, I'm not familiar with Kubernetes or helm.

**Comment by nroi** [comment]
@benedikt-bartscher as described in my previous comment, I need more details to make sure that what I implement is actually useful.

I'm closing this for now to keep the issue tracker clean, but I can reopen this once I have feedback from you or anyone else who's interested in this feature.

**Comment by bluser86** [comment]
Just to add my 2 cents to this: I was wondering the exact same thing and even thought of making a PR to add a health endpoint to the server, but then discovered through inspecting the code that it was in fact already there! It just wasn't documented anywhere in the README or the wiki. Perhaps it would be a good idea to add documentation concerning all available endpoints on the flexo server?
