### ISSUE TITLE
Compilation fails on FreeBSD

### ISSUE THREAD

**Issue by HorayNarea** [nroi/flexo#122]
**Describe the bug**
Compillation fails on FreeBSD (x86_64-unknown-freebsd) with the following error:

```
error[E0432]: unresolved import `libc::off64_t`
  --> src/main.rs:26:5
   |
26 | use libc::off64_t;
   |     ^^^^^^-------
   |     |     |
   |     |     help: a similar name exists in the module: `off_t`
   |     no `off64_t` in the root

error[E0425]: cannot find function `sendfile64` in crate `libc`
    --> src/main.rs:856:37
     |
856  |               let size: isize = libc::sendfile64(sfd, fd, &mut offset, count);
     |                                       ^^^^^^^^^^ help: a function with a similar name exists: `sendfile`
     |
    ::: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.155/src/unix/bsd/freebsdlike/mod.rs:1692:5
     |
1692 | /     pub fn sendfile(
1693 | |         fd: ::c_int,
1694 | |         s: ::c_int,
1695 | |         offset: ::off_t,
...    |
1699 | |         flags: ::c_int,
1700 | |     ) -> ::c_int;
     | |________________- similarly named function `sendfile` defined here

Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `flexo` (bin "flexo") due to 2 previous errors
```

**Installation method**
Manual compilation

**Distribution**
FreeBSD 13.4-RELEASE

**Version**
master branch

**Comment by nroi** [comment]
Just to clarify this upfront, I haven't made any effort so far to write flexo in a portable manner, it was always intended to be a Linux application. If it can be adapted to run on other Unix systems without too much effort, I'm willing to adapt it, but I'm not planning to spend much time on that.

Did you try to simply rename `sendfile64` to `sendfile`? Does that compile?

**Comment by HorayNarea** [comment]
I tried simply renaming the linux 64-bit specific functions/types to the BSD ones:

```diff
diff --git a/flexo/src/main.rs b/flexo/src/main.rs
index bf43b59..eaa4725 100644
--- a/flexo/src/main.rs
+++ b/flexo/src/main.rs
@@ -23,7 +23,7 @@ use crossbeam::channel::Receiver;
 use crossbeam::channel::RecvTimeoutError;
 use glob::glob;
 use humantime::format_duration;
-use libc::off64_t;
+use libc::off_t;
 #[cfg(test)]
 use tempfile::tempfile;

@@ -850,10 +850,10 @@ fn send_payload<T>(source: &mut File, filesize: u64, bytes_sent: i64, receiver:
     let fd = source.as_raw_fd();
     let sfd = receiver.as_raw_fd();
     let size = unsafe {
-        let mut offset = bytes_sent as off64_t;
+        let mut offset = bytes_sent as off_t;
         while (offset as u64) < filesize {
             let count = cmp::min(filesize as usize - offset as usize, MAX_SENDFILE_COUNT);
-            let size: isize = libc::sendfile64(sfd, fd, &mut offset, count);
+            let size: isize = libc::sendfile(sfd, fd, &mut offset, count);
             if size == -1 {
                 return Err(std::io::Error::last_os_error());
             }
```

but that also fails to compile:

```
root@archcache:~/src/flexo/flexo # cargo build --release
   Compiling flexo v1.6.9 (/root/src/flexo/flexo)
error[E0061]: this function takes 7 arguments but 4 arguments were supplied
    --> src/main.rs:856:31
     |
856  |             let size: isize = libc::sendfile(sfd, fd, &mut offset, count);
     |                               ^^^^^^^^^^^^^^-----------------------------
     |                                             |         |
     |                                             |         argument #3 of type `i64` is missing
     |                                             argument #5 of type `*mut sf_hdtr` is missing
     |                                             argument #7 of type `i32` is missing
     |
note: function defined here
    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.155/src/unix/bsd/freebsdlike/mod.rs:1692:12
     |
1692 |     pub fn sendfile(
     |            ^^^^^^^^
help: provide the arguments
     |
856  |             let size: isize = libc::sendfile(sfd, fd, /* i64 */, count, /* *mut sf_hdtr */, &mut offset, /* i32 */);
     |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0308]: mismatched types
   --> src/main.rs:856:31
    |
856 |             let size: isize = libc::sendfile(sfd, fd, &mut offset, count);
    |                       -----   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `isize`, found `i32`
    |                       |
    |                       expected due to this
    |
help: you can convert an `i32` to an `isize` and panic if the converted value doesn't fit
    |
856 |             let size: isize = libc::sendfile(sfd, fd, &mut offset, count).try_into().unwrap();
    |                                                                          ++++++++++++++++++++

Some errors have detailed explanations: E0061, E0308.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `flexo` (bin "flexo") due to 2 previous errors
```

As the `sendfile`s in
https://github.com/rust-lang/libc/blob/0a1eef9b89fa07a7655e50303caff13d59456f6c/src/unix/linux_like/linux/mod.rs#L5902
and
https://github.com/rust-lang/libc/blob/0a1eef9b89fa07a7655e50303caff13d59456f6c/src/unix/bsd/freebsdlike/mod.rs#L1701
have different arguments.

---

So I guess this is just unsupported for now.
Would be great to have something along the lines of "this is linux software only" in the README thou :sweat_smile:

Are you be open for PRs that make flexo more portable (at least for other unix-likes)?

**Comment by nroi** [comment]
>  Would be great to have something along the lines of "this is linux software only" in the README thou 😅

Fair enough, I'll add that. I just expected flexo users to use ArchLinux whenever possible :smiley: 

> Are you open for PRs that make flexo more portable (at least for other unix-likes)?

In general, yes, but robustness and maintainability have higher priority for me than portability, so:
* If somebody manages to create a PR that makes flexo compatible for FreeBSD (or another Unix) by adding a few lines of readable Rust code, and that OS-specific code is isolated in a single chunk of code rather, then yes, I would gladly accept this PR.
* If it adds more complexity than that, the answer is "it depends". I encourage everyone who works on such a PR to align their solution with me before spending too much time on it.

Another thing to keep in mind for those who intend to use flexo on a non-linux system: flexo uses this [bash script](https://github.com/nroi/flexo/blob/master/flexo_purge_cache) to clean the cache, which requires either paccache or [scruffy](https://github.com/nroi/scruffy) to be installed. So, if you want to have the cache-cleaning functionality, you'll probably want to get scruffy somehow running. scruffy contains very few lines of code, so I hope that won't be much of an issue.

**Comment by HorayNarea** [comment]
> Fair enough, I'll add that.

Thanks!

> I just expected flexo users to use ArchLinux whenever possible 😃

To be fair: I use ArchLinux (btw :smile:) on basically everything, but my home NAS is FreeBSD based for more than a decade now and has the spare storage to be a package cache for the many Arch-devices in the network without adding a new device (or Arch VM) that I would need to manage/keep up-to-date :D

> > Are you open for PRs that make flexo more portable (at least for other unix-likes)?
> 
> In general, yes, but robustness and maintainability have higher priority for me than portability

Understood! __If__ I find the time, I'll try to achieve a maintainable port to FreeBSD …don't expect anything in the near future :D

But first I will try a statically linked Linux-build of flexo and the [Linux Binary Compatibility of FreeBSD](https://docs.freebsd.org/en/books/handbook/linuxemu/) … :crossed_fingers: 
I'll report back here how that goes, in case someone else want's to run flexo on FreeBSD too.

> Another thing to keep in mind for those who intend to use flexo on a non-linux system: flexo uses this [bash script](https://github.com/nroi/flexo/blob/master/flexo_purge_cache) to clean the cache, which requires either paccache or [scruffy](https://github.com/nroi/scruffy) to be installed. So, if you want to have the cache-cleaning functionality, you'll probably want to get scruffy somehow running. scruffy contains very few lines of code, so I hope that won't be much of an issue.

Thanks for reminding me, I was aware of that but wanted to tackle the issue of cache purging once I got flexo to run :sweat_smile:

scruffy builds without problems on FreeBSD :) …but I can't tell if it would run fine, since I don't have a cache dir to test against

**Comment by nroi** [comment]
Great to know that at least scruffy compiles on FreeBSD.

>  I'll report back here how that goes, in case someone else want's to run flexo on FreeBSD too.

Interesting, yeah let us know how that goes.

I'll close this issue for now because for the moment, FreeBSD is not officially supported and this is also documented in the README.
