### ISSUE TITLE
Support to Serve Packages for ARM

### ISSUE THREAD

**Issue by cuberoot74088** [nroi/flexo#17]
Hi @nroi,

first of all thanks for further improving/evolving cpcache as flexo. :+1: 

I would like to ask if it would be possible to cache and serve packages for other architectures than `x86_64`, especially `arm*`?

I did a first quick try and it did not work. I also tried to add some arm mirror, but this also did not help.

Thanks.

**Comment by nroi** [comment]
Hi @cuberoot74088,

serving packages for ARM architectures is currently not supported. I've described a bit about why supporting ARM clients would require many changes: https://github.com/nroi/cpcache/issues/25
I'll see how many people leave a thumbs-up on this issue, so I might implement this in the future.

Just out of curiosity: What exactly is your use case, do you have many ARM devices, do you use ARM inside QEMU, or something completely different? I would have assumed that people who use ArchLinux ARM usually only have a single ARM device, so I didn't prioritize ARM client support for flexo or cpcache.

**Comment by cuberoot74088** [comment]
Hi,

thanks for the hint to the cpcache ticket. I have never thought about the mirror selection or redirections going on. Great, that flexo takes care of that!

Regarding the missing mirror json for ARM ... I would have hoped to be able to simply provide some mirrors manually via the  `mirrors_predefined = [ ]` list and let flexo choose the best from there - similar to what is happening for "normal" mirrors. But that did not work. 

Sure, very valid question. I currently have three raspberry pi running with ArchLinux ARM and would like to use the package cache similar to what "I am used to" for normal arch on x86_84. :innocent:

**Comment by ItsiAdam** [comment]
You can get the current list of http mirrors with their locations from here, I don't know why you have to set these headers to get the data, but whatever.

GET: `https://archlinuxarm.org/data/mirrors/list`
Header: `Referer: https://archlinuxarm.org/about/mirrors`
Header: `X-Requested-With: XMLHttpRequest`

Although I don't know if that is particularly useful to you, as you mentioned the official mirrorlist providing lots of quality related info, it does at least provide an up to date list of mirrors.

Might I propose flexo add functionality to generate it's own quality info using the list above, similar to what reflector does? The archlinux arm maintainers clearly have no interest in providing their own data.

**Comment by nroi** [comment]
> I don't know why you have to set these headers to get the data, but whatever.

The fact that this JSON endpoint is undocumented and requires these headers indicates that it's not meant to be used by third parties. So I assume that they are not committed to provide a stable API, so the JSON format or the address could change at any time. They might also introduce new methods to block requests that do not originate from the archlinuxarm website, so just setting those two headers may not be sufficient in the future.

If Arch Linux ARM does not provide an official endpoint for fetching mirror data, than I think it's best to just stick to the default method recommended by the Arch Linux ARM team (i.e., using `mirror.archlinuxarm.org` as your only mirror).

**Comment by nroi** [comment]
I have added a section in the README that describes how to use the `custom_repo` feature to fetch ARM packages from Flexo: https://github.com/nroi/flexo#serving-packages-for-arm-clients

I've tested this on my Raspberry PI and it seems to work well. But notice that you will only have the caching functionality of Flexo when you use the `custom_repo` feature, additional features like automatically selecting mirrors or automatically switching to a faster mirror are not available.

I don't use my Raspberry PI very often, so please comment if anything doesn't work well.

**Comment by cuberoot74088** [comment]
@nroi thanks, this working fine! 👍
