### ISSUE TITLE
Proposed project icon(?)

### ISSUE THREAD

**Issue by cmsigler** [nroi/flexo#32]
I'm not sure if this would qualify as "fair use" or not... however....

Please close if inappropriate; HTH :)

Clemmitt
![flexo_icon](https://user-images.githubusercontent.com/57174508/101484535-c6fe6280-3927-11eb-8d7a-835f059140d1.png)

**Comment by nroi** [comment]
Well, just copying the character is perhaps a bit unoriginal, but if someone with artistic talent wants to create a SVG that somehow resembles Flexo's beard, that would be…


![awesome_to_the_max](https://i.imgflip.com/18fzu8.jpg)

**Comment by cmsigler** [comment]
> ... if someone with artistic talent wants to create a SVG that somehow resembles Flexo's beard, that would be…
> AWESOME
> AWESOME TO THE MAX

Uh, I'm afraid to do that because I might contract... boneitis.... ;-O

**Comment by cmsigler** [comment]
...  Do you mean something like this?  Perhaps from a different viewing orientation....

![flexo_beard](https://user-images.githubusercontent.com/57174508/101818449-dc26ed00-3af1-11eb-8410-036f239f049e.png)

The bottom surface shouldn't be flat, is should be a cylindrical surface of a larger radius than the top surface.  But this gives you a rough idea.  I threw this together as a 3D model in OpenSCAD.

Please let me know if interested and I'll work on it in my spare time to do some simple surface texture mapping (in Blender?  I've never used Blender...) so it looks right :)

P.S.: No boneitis... YET :-O

Clemmitt

**Comment by nroi** [comment]
If you can throw something nice together without any effort, and you're doing it for the fun of it, then sure, I would add an SVG icon to the github page. But keep in mind that this icon could not be used anywhere else: Flexo has no webpage, it creates no menu entry or desktop icon, and there are no fancy graphs where the icon could be used. So I really wouldn't want anyone to spend too much time on this.

**Comment by cmsigler** [comment]
Hi again,

Not sure if this SVG will work right, but I'll give it the old college try....  Uh-oh.  I can't upload an SVG file, only 2d image/raster graphics.  So I'll export as a PNG and upload:

![flexo_beard_pointed_end_final_sm](https://user-images.githubusercontent.com/57174508/102104440-3084e200-3dfc-11eb-8cbd-5fa405b2b357.png)

Please let me know if this fills the bill, or if you want changes/refinements to lines or colors :)

I can say that the past few days haven't been fun due to a death in the family and this has helped take my mind off of things, which I truly appreciate!

Clemmitt

**Comment by nroi** [comment]
Hey,

I'm sorry to hear about that, I hope you'll feel better soon.

Thanks for the icon, it even has this "cartoonish" look :+1: 

If you can't upload an SVG in the issue tracker, can you please create a pull request and copy the SVG file into the root directory of the repo? I will then see how this icon should be embedded into the README.
