### ISSUE TITLE
Flexo cannot save and serve files on linux 5.10.3 and OpenZFS 2.0.0

### ISSUE THREAD

**Issue by cuberoot74088** [nroi/flexo#40]
Hi,

maybe this is more of an information...

I am using flexo with (zfs) linux 5.10.3 and OpenZFS 2.0.0, coming from 5.9.14 everything was working.

From my research, I found it is due to a change in the kernel and how zfs does (or not) implement sendfile (or some sort of directIO)...
(had the sendfile issue with nginx yesterday and had to remove it to get it up and running)

here is an link to the issue https://github.com/openzfs/zfs/issues/1156 and another PR working on directIO https://github.com/openzfs/zfs/pull/10018

So my guess is, that flexo does some kind of "directIO" and this is failing now (with my setup). 

However, I can confirm, it is still running with 5.10.3 and ext4 ...
So the problem is likely to be outside of flexo, I assume... but know you know about it ;-)

Thanks

**Comment by cuberoot74088** [comment]
The issue was solved (refs https://github.com/openzfs/zfs/pull/11378 and https://github.com/openzfs/zfs/pull/11351) and is available in the latest release OpenZFS 2.0.1 (https://github.com/openzfs/zfs/releases/tag/zfs-2.0.1).

As of today linux 5.10.5 and zfs 2.0.1 is available and flexo (and nginx) are working as before.

**Comment by nroi** [comment]
Good to hear, thanks for reporting this.
