### ISSUE TITLE
Support for custom repo (e.g. archzfs)?

### ISSUE THREAD

**Issue by n8henrie** [nroi/flexo#41]
Hello,

Thanks for the project! I have multiple Arch installs on my LAN and a single, very slow, internet connection, so I'm looking into options for package caching. A project in rust always catches my eye.

Is there support for custom repos like `archzfs`?

In contrast to `core` / `extra` / `community`, adding the flexo url to my `archzfs` section of `pacman.conf` seems not to work, resulting in:

```
error: failed retrieving file 'archzfs.db' from localhost:7878 : The requested URL returned error: 404
```

```
[archzfs]
Server = http://localhost:7878/$repo/os/$arch
Server = http://archzfs.com/$repo/$arch
...
```

I tried adding `http://archzfs.com/` to `mirrors_predefined` in `flexo.toml` with no change in behavior.

I see a few other issues mentioning `zfs` but nothing on the `archzfs` repo or adding custom repos.

Is using flexo to cache packages from custom repos possible?

**Comment by nroi** [comment]
Hi,

thanks for your feedback!

custom repos are currently not supported, but I'm optimistic that this can be implemented without much effort. I'll take a closer look this weekend.

**Comment by n8henrie** [comment]
Thanks for your time and attention!

**Comment by n8henrie** [comment]
Awesome, thank you!

**Comment by nroi** [comment]
You're welcome. Feel free to comment if something doesn't work as expected.

**Comment by n8henrie** [comment]
Seems to be working great. Thanks again.
