### ISSUE TITLE
Implement ipv6 functionality

### ISSUE THREAD

**Issue by cyorps** [nroi/flexo#47]
Feature-Request:
Can you implement that flexo works on ipv6-addresses too?

**Comment by nroi** [comment]
Just to clarify: Flexo already supports downloading from mirrors via IPv6, but you probably want Flexo to be able to listen on IPv6 addresses (i.e., `::1` as opposed to `127.0.0.1`). Is that correct?

**Comment by cyorps** [comment]
Using ipv6 upstream mirrors works like a charm (and the results of auto mirror selection astonishing me again and again). Exactly! I wan't to offer this protocol my own systems which using flexo as mirror.

For your clarification. Why I want to do this? I have 4 systems with more than 90% of incoming ipv6 connections from Internet. I will test and use these systems with ipv6 only. So! Indeed flexo with ipv6 is more a wish then hardly needed! 😉

**Comment by nroi** [comment]
Thanks for the feedback, it's always interesting to hear how people are using Flexo!

The new setting `listen_ip_address` has been included, so you can now add something like
```toml
listen_ip_address = "::"
```
or
```toml
listen_ip_address = "::1"
```
to `/etc/flexo/flexo.toml` below the `port` setting.
